lang = [
"I and you run quietly through the meadow and across the glacier under the bright lantern that glow softly before the hollow harbor",
"he and she see the nomad drift under the velvet horizon and they whisper gently because the breeze build through the harbor",
"I run quickly and quietly because the bright meadow and the soft glacier whisper to me",
"you build across the hollow and see the lantern glow but before the harbor you drift under the soft velvet",
"he and she run across the meadow quietly and gently because they feel the bright breeze under the hollow",
"the nomad build across the harbor and I see softly through the glacier before the lantern under the velvet across the meadow",
"they whisper quietly because the glow and the breeze run together and I build quickly through the hollow",
"she and I drift across the meadow under the bright lantern softly and gently through the harbor",
"you and he see the glacier before the nomad and they whisper under the velvet sky because the harbor glow quietly before the breeze",
"we all run across the meadow and build softly through the hollow because the bright lantern glow gently under the harbor",
"I drift under the velvet glacier and see the lantern glow quietly across the meadow",
"she and they build through the harbor softly because the breeze whisper across the hollow",
"he run quickly under the bright lantern and drift before the soft meadow",
"you whisper gently across the glacier and see the harbor glow under the velvet",
"I and he build softly through the meadow and across the hollow under the bright breeze",
"they see the nomad drift across the bright glacier quietly before the harbor",
"we all whisper under the velvet lantern because the breeze glow softly across the meadow",
"she drift quickly before the hollow and see the bright harbor glow gently",
"you and I run quietly across the glacier because the breeze build under the lantern",
"he build softly through the meadow under the bright velvet before the harbor glow",
"I and you whisper through the hollow quietly before the breeze drift across the meadow",
"they build under the glacier and see the lantern glow gently before the harbor",
"we all run softly across the bright meadow under the velvet breeze",
"he and I drift quickly through the hollow because the glow whisper under the harbor",
"she see the nomad across the glacier and quietly build before the bright lantern",
"you whisper softly through the breeze because the harbor glow gently under the hollow",
"they run across the meadow and build quietly under the velvet lantern",
"I drift through the bright breeze softly and see the glacier under the hollow",
"he and you see the harbor glow before the bright meadow and whisper quietly",
"she and they build across the glacier softly because the breeze drift through the harbor",
"we all run gently through the hollow before the bright lantern glow under the meadow",
"I build softly across the velvet glacier and see the nomad drift quietly",
"you and I run under the harbor through the meadow before the breeze glow softly",
"he whisper quietly because the bright glacier drift across the hollow under the lantern",
"she and I build quickly across the meadow under the velvet breeze before the harbor",
"they see the glow drift softly through the bright lantern and across the hollow",
"we all whisper gently under the harbor because the breeze build across the meadow",
"I run quietly through the soft hollow and see the glacier glow under the lantern",
"you drift gently across the bright meadow before the breeze whisper softly",
"he build through the harbor and see the velvet glow under the glacier",
"she and they run quietly across the meadow and build softly before the harbor",
"I and you whisper under the bright lantern before the hollow glow softly",
"they drift gently through the glacier and across the breeze before the harbor",
"we all see the nomad run quietly under the velvet meadow across the hollow",
"he and she build softly under the bright lantern because the harbor glow quietly",
"you whisper quickly before the glacier and drift under the breeze softly",
"I run gently across the meadow and see the lantern glow under the velvet",
"she and I build across the hollow softly before the harbor and bright breeze",
"they see the glacier glow under the lantern and run quietly through the meadow",
"we all drift across the bright hollow softly under the harbor before the breeze glow"
]
